project_id: "779500"
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: https://api.crowdin.com

preserve_hierarchy: true

files:
  # Strings
  - source: /composeApp/src/androidMain/res/values/strings.xml
    translation: /composeApp/src/androidMain/res/values-%android_code%/strings.xml
    languages_mapping:
      android_code:
        ia: ia
        sr: sr
        sr-CS: b+sr+Latn
  - source: /composeApp/src/composeResources/res/values/strings.xml
    translation: /composeApp/src/composeResources/res/values-%android_code%/strings.xml
    languages_mapping:
      android_code:
        ia: ia
  # Plurals
  - source: /composeApp/src/androidMain/res/values/plurals.xml
    translation: /composeApp/src/androidMain/res/values-%android_code%/plurals.xml
    languages_mapping:
      android_code:
        ia: ia
        sr: sr
        sr-CS: b+sr+Latn
  # FDroid fastlane - Full description
  - source: /fastlane/metadata/android/en-US/full_description.txt
    translation: /fastlane/metadata/android/%locale%/full_description.txt
    languages_mapping:
      locale:
        ia: ia
  # FDroid fastlane - Short description
  - source: /fastlane/metadata/android/en-US/short_description.txt
    translation: /fastlane/metadata/android/%locale%/short_description.txt
    languages_mapping:
      locale:
        ia: ia
