files:
  - source: /composeApp/src/androidMain/res/values/strings.xml
    translation: /composeApp/src/androidMain/res/values-%android_code%/strings.xml
    languages_mapping:
      android_code:
        zh-CN: zh-rCN
        zh-TW: zh-rTW
        pt-BR: pt-rBR
        sr: b+sr+Cyrl
        sr-CS: b+sr+Latn
  
  - source: /composeApp/src/androidMain/res/values/strings.xml
    translation: /composeApp/src/androidMain/res/values-%two_letters_code%/strings.xml
