name: Close issues upon a release.
on:
  release:
    types: [published]

jobs:
  patched:
    runs-on: ubuntu-latest
    steps:
      - name: Close issues marked as "patched" upon a release.
        uses: gcampbell-msft/fixed-pending-release@0.0.12
        with:
          token: ${{ secrets.CLOSE_ISSUE_ON_RELEASE }}
          label: patched
          message: >
            :tada: This issue has now been fixed and is available in [${releaseTag}](${releaseUrl}) :tada:

            This ticket is now closed. If you have any more question, feel free to reply below. If needed,
            the ticket will be re-open for further support.

  implemented:
    runs-on: ubuntu-latest
    steps:
      - name: Close issues marked as "implemented" upon a release.
        uses: gcampbell-msft/fixed-pending-release@0.0.12
        with:
          token: ${{ secrets.CLOSE_ISSUE_ON_RELEASE }}
          label: implemented
          message: >
            This request is already existed in the app. Therefore, this ticket is now closed.

            If you have any question, feel free to reply below. If needed,
            the ticket will be re-open for further support.
