name: Generate license & open pr to submit

on:

  push:
    paths:
      # Run this script when version of a
      # depency changes or modified.
      - 'gradle/libs.versions.toml'
    # Don't run on tag creation
    tags-ignore:
      - '**'

  workflow_dispatch:

jobs:
  vars:
    name: Generate date
    runs-on: ubuntu-latest

    # Set date as a variable
    outputs:
      date: ${{ steps.date.outputs.date }}
      branch_name: ${{ steps.branch.outputs.name }}

    steps:
      - name: Get date
        id: date
        # Output of "October 2 2024" will be "2024-10-02"
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Get branch name
        id: branch
        run: echo "name=licenses/automated-change-${{ steps.date.outputs.date }}" >> $GITHUB_OUTPUT


  create-pr:
    needs: vars
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true

      - name: Create new branch
        run: git checkout -b "${{ needs.vars.outputs.branch_name }}"

      - name: Setup Java 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Generate license report
        run: ./gradlew generateLicenseReport

      - name: Move license file into res/raw folder
        run: mv composeApp/build/reports/dependency-license/index.json composeApp/src/androidMain/res/raw/licenses.json

      - name: Check for changes
        id: git_status
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
        # 'continue-on-error: true' allows this step to not fail the workflow if no changes are found.
        continue-on-error: true

      # https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
      - name: Configure Git user
        if: steps.git_status.outputs.has_changes == 'true'
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Commit changes
        if: steps.git_status.outputs.has_changes == 'true'
        run: |
          git add composeApp/src/androidMain/res/raw/licenses.json
          git commit -m "licenses update ${{ needs.vars.outputs.date }}"

      - name: Push new branch
        if: steps.git_status.outputs.has_changes == 'true'
        run: git push origin ${{ needs.vars.outputs.branch_name }}

      - name: Create Pull Request
        if: steps.git_status.outputs.has_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            -t "Dependency licenses update" \
            -b "This pull request was automatically created by a GitHub Actions workflow to update licenses." \
            -B "main" \
            -H "${{ needs.vars.outputs.branch_name }}"
